wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1712655945.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 19
      - 23
      4: 3.12.2
      5: 0.16.6
      8:
      - 2
      - 3
      - 5
      13: windows-amd64
max_depth:
  desc: null
  value: 74
max_features:
  desc: null
  value: log2
min_samples_split:
  desc: null
  value: 6
n_estimators:
  desc: null
  value: 242
