version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    
    volumes:
      - .data:/src/data
      - ./savedModels:/src/savedModels
    
    environment:
      - FLASK_APP=test.py
