name: Daily Update Model

on:
  schedule:
    - cron: '33 11 * * *' # Every dayat 2.30 am (00h30 UTC)
    
jobs:
  update_data_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: develop
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install dependencies
      run: pip install -r api/dependencies.txt 

    - name: Copy files
      run: cp api/define_api_data.py api/updateTrain.py api/data/
    
    - name: DEbug message
      run: echo "Workflow triggered successfullyon branch ${{ github.ref }}"

    - name: Run Python Script
      run: python api/updateTrain.py

    
